Add terraform format and validation check in yaml file

diff --git a/.github/workflows/terraform.yml b/.github/workflows/terraform.yml
--- a/.github/workflows/terraform.yml
+++ b/.github/workflows/terraform.yml
@@ -27,6 +27,18 @@ jobs:
       uses: hashicorp/setup-terraform@v3
 #      with:
 #        terraform_version: 1.0.10
+    # Check terraform format for Push and PR on non-main branch
+    - name: Terraform fmt
+      id: fmt
+      if: github.ref != 'refs/heads/main'
+      run: terraform fmt -check
+  
+    # Run terraform validate for push and PR on non-main branch
+    # Run even-if terraform format is sucess or failure
+    - name: Terraform Validate
+      id: validate
+      if: github.ref != 'refs/heads/main' && (sucess() || failure())
+      run: terraform validate -no-color
 
     # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
     - name: Terraform Init
