moved terraform format and validate after terraform init in yaml

diff --git a/.github/workflows/terraform.yml b/.github/workflows/terraform.yml
--- a/.github/workflows/terraform.yml
+++ b/.github/workflows/terraform.yml
@@ -27,20 +27,7 @@ jobs:
       uses: hashicorp/setup-terraform@v3
 #      with:
 #        terraform_version: 1.0.10
-    # Check terraform format for Push and PR on non-main branch
-    - name: Terraform fmt
-      id: fmt
-      if: github.ref != 'refs/heads/main'
-      run: terraform fmt -check
-  
-    # Run terraform validate for push and PR on non-main branch
-    # Run even-if terraform format is sucess or failure
-    - name: Terraform Validate
-      id: validate
-      if: github.ref != 'refs/heads/main' && (success() || failure())
-      run: terraform validate -no-color
-
-    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
+# Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
     - name: Terraform Init
       id: init
       env:
@@ -53,6 +40,18 @@ jobs:
         CONTAINER_NAME: ${{ secrets.CONTAINER_NAME }}
       run: terraform init -upgrade -backend-config="storage_account_name=$STORAGE_ACCOUNT" -backend-config="container_name=$CONTAINER_NAME" -backend-config="resource_group_name=$RESOURCE_GROUP"
 
+    # Check terraform format for Push and PR on non-main branch
+    - name: Terraform fmt
+      id: fmt
+      if: github.ref != 'refs/heads/main'
+      run: terraform fmt -check
+  
+    # Run terraform validate for push and PR on non-main branch
+    # Run even-if terraform format is sucess or failure
+    - name: Terraform Validate
+      id: validate
+      if: github.ref != 'refs/heads/main' && (success() || failure())
+      run: terraform validate -no-color
 
     # Run a terraform plan for pull requests only
     - name: Terraform Plan
